// Static client-side copy of module metadata.
// Keeps the landing page a pure client component (progress hook needs it)
// without fs reads on the client.

import type { ModuleMeta } from './modules'

export const MODULES_CLIENT: ModuleMeta[] = [
  {
    slug: 'what-is-ai',
    title: 'What AI actually is',
    order: 1,
    level: 'beginner',
    duration: '8 min',
    summary: 'Not magic, not a robot. A very good guesser trained on patterns in human writing.',
    tags: ['fundamentals'],
  },
  {
    slug: 'how-llms-work',
    title: 'How a language model works',
    order: 2,
    level: 'beginner',
    duration: '10 min',
    summary: 'Predicting the next word, one at a time. Why that simple idea produces something so capable.',
    tags: ['fundamentals'],
  },
  {
    slug: 'tokens-and-context',
    title: 'Tokens & context windows',
    order: 3,
    level: 'beginner',
    duration: '8 min',
    summary: 'Why AI sometimes forgets what you said — and how to work with that, not against it.',
    tags: ['fundamentals', 'prompting'],
  },
  {
    slug: 'prompting-for-designers',
    title: 'Prompting for designers',
    order: 4,
    level: 'beginner',
    duration: '12 min',
    summary: 'Structure your requests like a brief. Role, task, format, constraints — and examples.',
    tags: ['prompting', 'practical'],
  },
  {
    slug: 'what-ai-can-and-cant-do',
    title: 'What AI can and cannot do',
    order: 5,
    level: 'beginner',
    duration: '10 min',
    summary: 'An honest map of capabilities and limits, with interior design examples throughout.',
    tags: ['fundamentals'],
  },
  {
    slug: 'provider-landscape',
    title: 'The provider landscape',
    order: 6,
    level: 'beginner',
    duration: '8 min',
    summary: 'Claude, ChatGPT, Midjourney — how to choose by what you need, not by what is trending.',
    tags: ['tools'],
  },
  {
    slug: 'agents-and-tools',
    title: 'Agents, tools & skills',
    order: 7,
    level: 'intermediate',
    duration: '10 min',
    summary: 'What "agent" actually means. What MCP is. Where the skills Arnau built fit in.',
    tags: ['tools', 'advanced'],
  },
  {
    slug: 'image-models',
    title: 'Image models',
    order: 8,
    level: 'intermediate',
    duration: '9 min',
    summary: 'How diffusion works. What image AI is great for — and why it still struggles with fingers.',
    tags: ['tools', 'visual'],
  },
  {
    slug: 'design-workflows',
    title: 'Workflows for interior design',
    order: 9,
    level: 'intermediate',
    duration: '12 min',
    summary: 'Five concrete recipes: palette from a photo, accessibility pass, email rewriter, and more.',
    tags: ['practical', 'workflows'],
  },
  {
    slug: 'staying-current',
    title: 'Staying current without the hype',
    order: 10,
    level: 'intermediate',
    duration: '8 min',
    summary: 'How to evaluate any new AI tool in 10 minutes. Principles outlast products.',
    tags: ['mindset'],
  },
]
